
package mp3player;

import java.io.File;
import java.io.FileFilter;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.Files.list;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import static java.rmi.Naming.list;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.attr;
import static javax.management.Query.attr;
import javax.swing.table.DefaultTableModel;
import org.farng.mp3.MP3File;
import org.farng.mp3.id3.ID3v1;

/**
 *
 * @author Niels
 */
public class Mp3PlayerGUI extends javax.swing.JFrame {

    MainClass MC = new MainClass();
    public Mp3PlayerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStop = new javax.swing.JLabel();
        jLabelPlay = new javax.swing.JLabel();
        jLabelPause = new javax.swing.JLabel();
        jTextFieldDisplay = new javax.swing.JTextField();
        jButtonMusic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMusicLib = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 700));
        getContentPane().setLayout(null);

        jLabelStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/Stop Icon.png"))); // NOI18N
        jLabelStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelStopMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelStopMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelStop);
        jLabelStop.setBounds(40, 40, 110, 110);

        jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/Play Icon.png"))); // NOI18N
        jLabelPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPlayMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPlay);
        jLabelPlay.setBounds(150, 40, 110, 110);

        jLabelPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/Pause Icon.png"))); // NOI18N
        jLabelPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPauseMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPause);
        jLabelPause.setBounds(260, 40, 110, 110);

        jTextFieldDisplay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDisplay);
        jTextFieldDisplay.setBounds(70, 0, 270, 30);

        jButtonMusic.setText("Select Music");
        jButtonMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMusicActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMusic);
        jButtonMusic.setBounds(290, 160, 100, 25);

        jTableMusicLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Album", "Artist", "Duration"
            }
        ));
        jTableMusicLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMusicLibMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableMusicLibMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMusicLib);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 10, 590, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStopMousePressed

    }//GEN-LAST:event_jLabelStopMousePressed

    private void jLabelPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayMouseReleased

    MC.Resume();
    }//GEN-LAST:event_jLabelPlayMouseReleased

    private void jLabelStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStopMouseReleased
    MC.Stop();
    }//GEN-LAST:event_jLabelStopMouseReleased

    private void jLabelPauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPauseMouseReleased
    MC.Pause();
    }//GEN-LAST:event_jLabelPauseMouseReleased

    private void jTextFieldDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDisplayActionPerformed

    private void jButtonMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMusicActionPerformed
    FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3", "mpeg3");
    
    
    JFileChooser chooser = new JFileChooser("C:\\Users\\Niels\\Documents\\NetBeansProjects\\mp3Player\\Music");
    chooser.addChoosableFileFilter(filter);
    chooser.setAcceptAllFileFilterUsed(false);
    
    int returnVal = chooser.showOpenDialog(null);
    
    if (returnVal == JFileChooser.APPROVE_OPTION)   
    {
        MC.Stop();
        File myFile = chooser.getSelectedFile();
        String song = myFile + "";
        
        String name = chooser.getSelectedFile().getName();
        String album = chooser.getSelectedFile().getName();
        jTextFieldDisplay.setText(name);
        jTableMusicLib.setValueAt(name,0,0);
        jTableMusicLib.setValueAt(album,0,1);
        
        MC.Play(song);
    }
    Mp3File mp3file = new Mp3File(chooser);
    if (mp3file.hasId3v1Tag()) {
    ID3v1 id3v1Tag = mp3file.getId3v1Tag();
    System.out.println("Artist: " + id3v1Tag.getArtist());
    System.out.println("Title: " + id3v1Tag.getTitle());
    System.out.println("Album: " + id3v1Tag.getAlbum());
    System.out.println("Year: " + id3v1Tag.getYear());
    System.out.println("Comment: " + id3v1Tag.getComment());
}
    }//GEN-LAST:event_jButtonMusicActionPerformed

    private void jTableMusicLibMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMusicLibMouseReleased
    jTableMusicLib.setEnabled(false);
    
    }//GEN-LAST:event_jTableMusicLibMouseReleased

    private void jTableMusicLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMusicLibMouseClicked
    
    }//GEN-LAST:event_jTableMusicLibMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mp3PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mp3PlayerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonMusic;
    private javax.swing.JLabel jLabelPause;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JLabel jLabelStop;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMusicLib;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
